version: '3.8'

services:
  inventory:
    build:
      context: ./Inventory
      dockerfile: Dockerfile
    image: matthew160619/inventory:1.0
    environment:
      - TABLE_NAME=Inventory
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    ports:
      - "5006:5000"

  excess_inventory:
    image: matthew160619/inventory:1.0
    environment:
      - TABLE_NAME=Excess_Inventory
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    ports:
      - "5001:5000"

  notification:
    build:
      context: ./Notification
      dockerfile: Dockerfile
    image: matthew160619/notification:1.0
    environment:
      - TABLE_NAME=Notification
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    ports:
      - "5002:5000"