version: '3.8'

services:
  inventory:
    build:
      context: ./Inventory
      dockerfile: Dockerfile
    image: matthew160619/inventory:1.0
    environment:
      - TABLE_NAME=Inventory
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    ports:
      - "${INVENTORY_PORT}:5000"

  excess_inventory:
    image: matthew160619/inventory:1.0
    environment:
      - TABLE_NAME=Excess_Inventory
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    ports:
      - "${EXCESS_INVENTORY_PORT}:5000"

  notification:
    build:
      context: ./Notification
      dockerfile: Dockerfile
    image: matthew160619/notification:1.0
    environment:
      - TABLE_NAME=Notification
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
    ports:
      - "${NOTIFICATION_PORT}:5000"

  route-optimizer:
    build:
      context: ./route
      dockerfile: Dockerfile
    environment:
      - ONEMAP_EMAIL=${ONEMAP_EMAIL}
      - ONEMAP_PASSWORD=${ONEMAP_PASSWORD}
      # - OPENCAGE_API=${OPENCAGE_API}
    ports:
      - "${ONEMAP_PORT}:5003"
    networks:
      - route
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  route:
    driver: bridge
