services:
  route-optimizer:
    build: .
    ports:
      - "5003:5003"
    networks:
      - route
    environment:
      - ONEMAP_EMAIL=${ONEMAP_EMAIL}
      - ONEMAP_PASSWORD=${ONEMAP_PASSWORD}

networks:
  route: 
    driver: bridge
