version: '3.8'

services:
  resource-allocation-service:
    build: .
    container_name: resource-allocation-service
    # network_mode: "host"  # Use the host network
    environment:
    - INVENTORY_ENDPOINT=http://host.docker.internal:5006/inventory/
    - EXCESS_INVENTORY_ENDPOINT=http://host.docker.internal:5001/inventory/
    - ROUTE_ENDPOINT=http://host.docker.internal:5003/route_from_recipients
    - CHARITY_RECIPIENT_ENDPOINT=https://personal-d4txim0d.outsystemscloud.com/Recipient/rest/RecipientAPI/GetRecipientByCharityID?CharityID=
    restart: unless-stopped
    ports:
      - "8000:8000"